import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime
import os

# -------------------------------
# FILES
# -------------------------------
LOG_FILE = "logs.csv"
PDF_FILE = "ALM_Report.pdf"
SPEECH_CM = "speech_confusion_matrix.png"
SOUND_CM = "sound_confusion_matrix.png"

# -------------------------------
# LOAD DATA
# -------------------------------
df = pd.read_csv(LOG_FILE)

styles = getSampleStyleSheet()
story = []

def add_title(text):
    story.append(Spacer(1, 20))
    story.append(Paragraph(text, styles["Title"]))
    story.append(Spacer(1, 20))

def add_section(title, body):
    story.append(Paragraph(title, styles["Heading2"]))
    story.append(Spacer(1, 10))
    story.append(Paragraph(body, styles["BodyText"]))
    story.append(Spacer(1, 15))

# -------------------------------
# PDF SETUP
# -------------------------------
pdf = SimpleDocTemplate(PDF_FILE, pagesize=A4)

# -------------------------------
# CONTENT
# -------------------------------
add_title("Real-Time Deep Learning Audio Language Model (ALM)")

add_section("Author & Date",
            f"Generated by Student\nDate: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

add_section("Abstract",
"""
This project presents a real-time Deep Learning based Audio Language Model (ALM) that listens to live microphone input,
classifies both speech and non-speech sounds, and performs contextual reasoning using a memory-based engine.
The system integrates deep learning inference, web-based visualization, logging, and automated evaluation.
""")

add_section("Dataset Description",
"""
Speech Dataset:
Google Speech Commands dataset used for training speech recognition models.

Sound Dataset:
Environmental sound samples including sirens, horns, noise, silence, and natural sounds.

Both datasets are processed using MFCC (Mel-Frequency Cepstral Coefficients) feature extraction.
""")

add_section("Model Architecture",
"""
The ALM uses a shared neural network backbone with two output heads:
1. Speech Classification Head
2. Sound Classification Head

The shared layers learn a joint audio representation which is then specialized for both speech and sound tasks.
""")

# -------------------------------
# ACCURACY
# -------------------------------
speech_acc = (df["true_speech"] == df["speech"]).mean() * 100
sound_acc = (df["true_sound"] == df["sound"]).mean() * 100

add_section("Evaluation Results",
f"""
Speech Accuracy: {speech_acc:.2f}%
Sound Accuracy: {sound_acc:.2f}%

Confusion matrices are provided in the following pages to visualize classification performance.
""")

# -------------------------------
# CONFUSION MATRIX IMAGES
# -------------------------------
story.append(PageBreak())

if os.path.exists(SPEECH_CM):
    story.append(Paragraph("Speech Confusion Matrix", styles["Heading2"]))
    story.append(Spacer(1, 10))
    story.append(Image(SPEECH_CM, width=400, height=400))
    story.append(PageBreak())

if os.path.exists(SOUND_CM):
    story.append(Paragraph("Sound Confusion Matrix", styles["Heading2"]))
    story.append(Spacer(1, 10))
    story.append(Image(SOUND_CM, width=400, height=400))
    story.append(PageBreak())

# -------------------------------
# SMART CONTEXT ENGINE
# -------------------------------
add_section("Smart Context Engine",
"""
The system maintains a rolling memory of recent predictions and applies confidence-based and pattern-based rules.
Examples include emergency detection from repeated sirens, obstacle alerts from stop commands combined with noise,
and low-confidence handling to request repeated input.
""")

add_section("Conclusion",
"""
This project demonstrates the integration of deep learning, real-time audio processing, web technologies,
and contextual reasoning into a unified Audio Language Model framework.
The system is suitable for intelligent assistants, traffic monitoring, and safety-critical audio applications.
""")

# -------------------------------
# BUILD PDF
# -------------------------------
pdf.build(story)

print("📄 PDF GENERATED:", PDF_FILE)
